"""create users and daily songs

Revision ID: 9b9c1c4f5780
Revises: 
Create Date: 2026-07-12 09:59:12.642651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9c1c4f5780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.create_table('daily_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=255), nullable=True),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('spotify_url', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('criteria_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR anonymous_id IS NOT NULL', name='ck_daily_songs_user_or_anonymous'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_songs_anonymous_id'), 'daily_songs', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_daily_songs_user_id'), 'daily_songs', ['user_id'], unique=False)
    op.create_index('uq_daily_songs_anonymous_date', 'daily_songs', ['anonymous_id', 'date'], unique=True, postgresql_where=sa.text('anonymous_id IS NOT NULL'))
    op.create_index('uq_daily_songs_user_date', 'daily_songs', ['user_id', 'date'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_daily_songs_user_date', table_name='daily_songs', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_daily_songs_anonymous_date', table_name='daily_songs', postgresql_where=sa.text('anonymous_id IS NOT NULL'))
    op.drop_index(op.f('ix_daily_songs_user_id'), table_name='daily_songs')
    op.drop_index(op.f('ix_daily_songs_anonymous_id'), table_name='daily_songs')
    op.drop_table('daily_songs')
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
